cr-dump: add compel/ptrace.h include
Need in PTRACE_PEEKSIGINFO declarations:
criu/cr-dump.c: In function ‘dump_signal_queue’:
criu/cr-dump.c:901:16: error: ‘PTRACE_PEEKSIGINFO_SHARED’ undeclared (first use in this function)
   arg.flags |= PTRACE_PEEKSIGINFO_SHARED;
                ^
criu/cr-dump.c:901:16: note: each undeclared identifier is reported only once for each function it appears in
criu/cr-dump.c:920:21: error: ‘PTRACE_PEEKSIGINFO’ undeclared (first use in this function)
   nr = ret = ptrace(PTRACE_PEEKSIGINFO, tid, &arg, si);
                     ^

Can be squashed with commit 638b0c2f11e1 ("compel: Move in parasite
engine").

Cc: Cyrill Gorcunov <gorcunov@openvz.org>
Signed-off-by: Dmitry Safonov <dsafonov@virtuozzo.com>
Signed-off-by: Pavel Emelyanov <xemul@virtuozzo.com>