compel/arm64: rename gcs_context to avoid conflicts with system headers
In file included from compel/plugins/std/infect.c:14:
compel/include/uapi/compel/asm/sigframe.h:17:8: error: redefinition of 'gcs_context'
   17 | struct gcs_context {
      |        ^
/usr/include/aarch64-linux-gnu/asm/sigcontext.h:188:8: note: previous definition is here
  188 | struct gcs_context {
      |        ^

Signed-off-by: Andrei Vagin <avagin@google.com>