soccr: add one more test to check libsoccr_save/libsoccr_restore
[root@fc24 test]# valgrind ./tcp-conn
==31562== Memcheck, a memory error detector
==31562== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==31562== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==31562== Command: ./tcp-conn
==31562==
==31562== Warning: noted but unhandled ioctl 0x894b with no size/direction hints.
==31562==    This could cause spurious value errors to appear.
==31562==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
Debug: 	Setting 1 queue seq to 2004100269
Debug: 	Setting 2 queue seq to 2651007575
Debug: 	Restoring TCP options
Debug: 		Will turn SAK on
Debug: 		Will set snd_wscale to 7
Debug: 		Will set rcv_wscale to 7
Debug: 		Will turn timestamps on
Debug: Will set mss clamp to 65495
Debug: 	Restoring TCP 1 queue data 11 bytes
Error: Failed to turn off repair mode on socket: Bad file descriptor
==31562==
==31562== HEAP SUMMARY:
==31562==     in use at exit: 0 bytes in 0 blocks
==31562==   total heap usage: 4 allocs, 4 frees, 1,116 bytes allocated
==31562==
==31562== All heap blocks were freed -- no leaks are possible
==31562==
==31562== For counts of detected and suppressed errors, rerun with: -v
==31562== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)