vdso: handle s390x correctly
On s390x there is currently a build failure:

criu/pie/util-vdso.c: In function ‘elf_symbol_lookup’:
criu/pie/util-vdso.c:313:31: error: initialization of ‘uint32_t *’ {aka ‘unsigned int *’} from incompatible pointer type ‘Hash_t *’ {aka ‘long unsigned int *’} [-Wincompatible-pointer-types]
  313 |                 uint32_t *h = bucket + nbucket + (j - sym_off);
      |                               ^~~~~~

Replacing uint32_t with Hash_t which is defined behind a architecture
specific ifdef solves this error.

Signed-off-by: Adrian Reber <areber@redhat.com>